[package]
name = "external"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust_decimal = "1.29.1"
rust_decimal_macros = "1.29.1"
# mockito = "0.30.0"
reqwest = { version = "0.11.6", features = ["blocking", "json"] }
serde = { version = "1.0.130", features = ["derive"] }
async-trait = "0.1.50"
# tokio = "1.27.0"
tokio = { version = "1.27.0", features = ["macros", "sync"] }
# tokio-tungstenite = "0.15"
tokio-tungstenite-wasm = "0.1.0"
futures-util = "0.3.17"

core_pkg = {package = "core", path = "../core" }
serde_json = "1.0.96"
# warp = "0.3.3"

